from overhave.transport import GitlabMrCreationResponse


class TestGitlabHttpClientModels:
    """ Unit tests for :class:`GitlabHttpClient` models. """

    def test_mr_creation_response(self) -> None:
        GitlabMrCreationResponse.parse_obj(
            {
                "id": 285054,
                "iid": 381,
                "project_id": 2034,
                "title": "lyl",
                "description": None,
                "state": "opened",
                "created_at": "2021-06-04T07:50:56.457Z",
                "updated_at": "2021-06-04T07:50:56.457Z",
                "target_branch": "kekekse",
                "source_branch": "test2",
                "upvotes": 0,
                "downvotes": 0,
                "author": {
                    "id": 3320,
                    "name": "Рогов Артемий Андреевич",
                    "username": "a.rogov",
                    "state": "active",
                    "avatar_url": "https://gitlab.example.ru/uploads/-/system/user/avatar/3320/avatar.png",
                    "web_url": "https://gitlab.example.ru/a.rogov",
                },
                "assignees": [],
                "assignee": None,
                "reviewers": [],
                "source_project_id": 2034,
                "target_project_id": 2034,
                "labels": [],
                "work_in_progress": False,
                "milestone": None,
                "merge_when_pipeline_succeeds": False,
                "merge_status": "checking",
                "sha": None,
                "merge_commit_sha": None,
                "squash_commit_sha": None,
                "discussion_locked": None,
                "should_remove_source_branch": None,
                "force_remove_source_branch": None,
                "reference": "!381",
                "references": {"short": "!381", "relative": "!381", "full": "kek/kek-features!381"},
                "web_url": "https://gitlab.example.ru/kek/kek-features/-/merge_requests/381",
                "time_stats": {
                    "time_estimate": 0,
                    "total_time_spent": 0,
                    "human_time_estimate": None,
                    "human_total_time_spent": None,
                },
                "squash": False,
                "task_completion_status": {"count": 0, "completed_count": 0},
                "has_conflicts": False,
                "blocking_discussions_resolved": True,
                "approvals_before_merge": None,
                "subscribed": True,
                "changes_count": None,
                "latest_build_started_at": None,
                "latest_build_finished_at": None,
                "first_deployed_to_production_at": None,
                "pipeline": None,
                "head_pipeline": None,
                "diff_refs": None,
                "merge_error": None,
                "user": {"can_merge": True},
            }
        )
