ARG IMAGE_BASE
ARG POETRY_CONTENT_HASH
ARG DOCKER_HUB_PROXY

FROM ${IMAGE_BASE}bds/overhave-base:${POETRY_CONTENT_HASH}

COPY ./overhave /code/overhave
COPY ./docs /code/docs
COPY ./tests /code/tests
COPY ./makefile /code/makefile
COPY ./mypy.ini /code/mypy.ini
COPY ./README.md /code/README.md

CMD ["tox", "-v"]