ARG IMAGE_BASE
ARG POETRY_CONTENT_HASH

FROM ${IMAGE_BASE}overhave-base:${POETRY_CONTENT_HASH}

COPY ./overhave /code/overhave
COPY ./docs /code/docs
COPY ./tests /code/tests
COPY ./makefile /code/makefile
COPY ./mypy.ini /code/mypy.ini
COPY ./README.rst /code/README.rst

CMD ["tox", "-v"]